name: Daily Data Update
on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정 실행
  workflow_dispatch: # 수동 실행 버튼 추가

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: {python-version: '3.9'}
      - run: |
          pip install pandas FinanceDataReader
          python update_data.py
      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/stock_list.csv
          git commit -m "Update stock data"
          git push
